### ISSUE TITLE
Add ing trim_newlines and trim_whitespace

### ISSUE THREAD

**Issue by sscherfke** [nvimtools/none-ls-extras.nvim#5]
Null-ls used to contain the `trim_newlines` and `trim_whitespace` formatters which were ditched in favor of `editorconfig`.

Both formatters are quite simple and it would be cool if they could be added here for the people that don't want (or cannot) use `editorconfig`.

See: https://github.com/nvimtools/none-ls.nvim/blob/f9ca1200102655b21d0d6cc7648917e054d3e123/lua/null-ls/builtins/formatting.lua#L616-L636

**Comment by mochaaP** [comment]
Sure, will do it later :)

**Comment by mochaaP** [comment]
Done in 4d1b26b963edb82c45ed261d988f9e72253c3469

**Comment by sscherfke** [comment]
"later" 😅 

Thanks for the quick resolution. ❤️
